services:
  keycloak:
    build: .
    container_name: keycloak-pharosai-theme
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: true
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      # Mount theme for development (optional - for live editing)
      - ./pharosai-theme:/opt/keycloak/themes/pharosai-theme:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
